apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: web
  name: web
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    apps.kubernetes.io/name: nginx
status:
  loadBalancer: {}