apiVersion: apps/v1
kind: Deployment
metadata:

  name: nginx
  labels:
    apps.kubernetes.io/name: nginx
    apps.kubernetes.io/app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      apps.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        apps.kubernetes.io/name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: web
  name: web
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    apps.kubernetes.io/name: nginx
status:
  loadBalancer: {}